# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-c5eZ1jkYqquH2qa0Vv8S5y8EDMpAz0
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y, 'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,6,8])
y=np.array([3,8,1,10])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]


plt.plot(x, y)


plt.title('Oddiy Chiziqli Grafik')


plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')


plt.show()

import matplotlib.pyplot as plt


x = [1, 2, 3, 4, 5]
y = [5, 4, 3, 2, 1]


plt.scatter(x, y)


plt.title('Marifova Muslimabonu')


plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')


plt.show()

import matplotlib.pyplot as plt


x = [1, 2, 3, 4, 5]
y = [5, 4, 3, 2, 1]


plt.scatter(x, y)


plt.title('Scatter Diagramma')


plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')


plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
plt.scatter(x,y,color='red')
x=np.array([12,6,8,11,8,3])
y=np.array([5,6,3,7,17,19])
plt.scatter(x,y,color='green')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([35,25,25,15])
plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['A','B','C','D'])
y=np.array([3,8,1,10])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])

plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels=["Apples","Bananas",
"Cherries","Dates" ]

plt.pie(y,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels=["Apples","Bananas","Cherries",
"Dates" ]
myexplode=[0.2,0,0,0]
plt.pie(y,labels= mylabels,startangle=90,
explode=myexplode,shadow=True)
plt.show()